name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: setup go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: go.mod
    - name: release
      run: |
        make crossbuild upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
    - uses: haya14busa/action-update-semver@7d2c558640ea49e798d46539536190aff8c18715 # v1.5.1
      with:
        major_version_tag_only: true
