name: reviewdog
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: reviewdog/action-staticcheck@53efac7da6eead83fb445fc490fef0b7ea57eeb1 # v1.31.0
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        fail_on_error: true
