name: reviewdog
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: reviewdog/action-staticcheck@564f18c6297af36f7b10b6c7a72e814341bd813a # v1.29.0
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        fail_on_error: true
