name: tagpr-gh2changelog
on:
  push:
    branches:
    - "main"
    paths:
    - "gh2changelog/**"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  issues: read
jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        permission-contents: write
        permission-pull-requests: write
        permission-issues: read
    - name: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
        token: ${{ steps.generate_token.outputs.token }}
    - name: tagpr
      uses: Songmu/tagpr@9bbb945b2fb025126186661e27d55485e3fc6df6 # v1.18.3
      with:
        config: gh2changelog/.tagpr
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
